#!/usr/bin/env bash
#
# =============================================================================
#  generate-tagrules.sh  --  auto-generate per-monitor tile/float tagrules
# =============================================================================
#  mango stores per-monitor tile/float mode as `tagrule` lines keyed by the
#  LITERAL output name (one rule per tag, 9 tags per monitor). Those names differ
#  per machine and mango can't auto-detect them from the config, so historically
#  you had to hand-edit a MONITOR-1 template. This script does it for you: it asks
#  the RUNNING compositor for the currently-connected outputs and writes a ready-
#  to-source tagrules file.
#
#  Every monitor defaults to TILE mode. Toggle a monitor to FLOAT later with the
#  Monitor Mode bar plugin (or set-monitor-mode.sh) -- no need to decide here; that
#  toggle rewrites the matching block in this file.
#
#  SAFE TO RE-RUN anytime (after docking a laptop, plugging/unplugging a monitor,
#  etc.): it OVERWRITES the file with your current outputs -- never appends or
#  duplicates. Reload mango afterwards (mmsg dispatch reload_config, or Super+r).
#
#  Output:  ~/.config/mango/dms/tagrules.conf   (sourced by config.conf)
#  Usage:   ~/.config/mango/scripts/generate-tagrules.sh
#
#  Needs mango RUNNING (it queries the live compositor for outputs via mmsg).
# =============================================================================
set -uo pipefail

# ---- ########## EDIT HERE AFTER A MANGO UPDATE ########## -------------------
# The query that lists connected output NAMES -- the SAME call the Window Mode
# plugin and post-update-health.sh use. If output detection breaks after a mango
# update, verify by hand:   mmsg get all-monitors | jq '.monitors[].name'
OUTPUTS_CMD=(mmsg get all-monitors)
outputs_names() { "${OUTPUTS_CMD[@]}" 2>/dev/null | jq -r '.monitors[].name' 2>/dev/null; }
TAGS_PER_MONITOR=9                 # mango has 9 tags per monitor
# ----------------------------------------------------------------------------

OUT_FILE="$HOME/.config/mango/dms/tagrules.conf"

die() { echo "generate-tagrules: $*" >&2; exit 1; }

command -v mmsg >/dev/null 2>&1 || die "mmsg not found -- is MangoWM installed and running?"
command -v jq   >/dev/null 2>&1 || die "jq not found -- install jq (it's in the DankMango package list)."

mkdir -p "$(dirname "$OUT_FILE")"

# Collect current outputs, sorted + de-duplicated so re-runs produce an identical
# file regardless of the order mmsg happens to return them in.
mapfile -t MONITORS < <(outputs_names | sed '/^[[:space:]]*$/d' | sort -u)

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# ==========================================================================="
  echo "# tagrules.conf  --  AUTO-GENERATED by scripts/generate-tagrules.sh."
  echo "# DO NOT hand-edit: re-run that script instead (e.g. after adding/removing a"
  echo "# monitor). The Monitor Mode plugin / set-monitor-mode.sh may rewrite these"
  echo "# lines to toggle a monitor between tile and float."
  echo "# Generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "#"
  echo "# One 9-line block per connected monitor, all defaulting to TILE. A monitor"
  echo "# FLOATS when its rules gain ', open_as_floating:1' (added by the toggle)."
  echo "# Sourced by config.conf:  source=~/.config/mango/dms/tagrules.conf"
  echo "# ==========================================================================="
  if [ "${#MONITORS[@]}" -eq 0 ]; then
    echo "# (no connected outputs detected at generation time -- is mango running?)"
  fi
  for mon in "${MONITORS[@]}"; do
    echo ""
    echo "# --- $mon (tile) ---"
    for id in $(seq 1 "$TAGS_PER_MONITOR"); do
      echo "tagrule = id:$id, monitor_name:$mon, layout_name:tile"
    done
  done
} > "$TMP"

mv "$TMP" "$OUT_FILE"

# --- summary ----------------------------------------------------------------
if [ "${#MONITORS[@]}" -eq 0 ]; then
  echo "generate-tagrules: WARNING -- no outputs detected; wrote a header-only $OUT_FILE."
  echo "                   Is mango running? Re-run this once your session is up."
  exit 0
fi
echo "generate-tagrules: detected ${#MONITORS[@]} monitor(s): ${MONITORS[*]}"
echo "                   wrote $(( ${#MONITORS[@]} * TAGS_PER_MONITOR )) tagrule line(s), all TILE -> $OUT_FILE"
echo "                   reload mango to apply:  mmsg dispatch reload_config   (or Super+r)"
