#!/usr/bin/env bash
#
# =============================================================================
#  generate-tagrules.sh  --  auto-generate the per-monitor layout tagrules
# =============================================================================
#  mango stores a monitor's tiling layout as `tagrule` lines keyed by the LITERAL
#  output name (one rule per tag, 9 tags per monitor). Those names differ per
#  machine and mango can't work them out from the config on its own, so you used
#  to have to hand-edit a MONITOR-1 template. This does it for you: it asks the
#  RUNNING compositor which outputs are connected and writes a ready-to-source
#  tagrules file.
#
#  Every monitor starts on the TILE layout. Pick a different one per monitor later
#  from the Monitor Mode bar plugin (or set-monitor-layout.sh) -- nothing to decide
#  here; that rewrites the matching block in this file.
#
#  SAFE TO RE-RUN any time (after docking a laptop, plugging or unplugging a
#  monitor, etc.): it OVERWRITES the file with your current outputs -- it never
#  appends or duplicates. Reload mango afterwards (mmsg dispatch reload_config,
#  or Super+r).
#
#  Worth knowing: a bare re-run resets every monitor to tile. monitor-watcher.sh
#  is the path that captures your layouts first and puts them back after.
#
#  Output:  ~/.config/mango/dms/tagrules.conf   (sourced by config.conf)
#  Usage:   ~/.config/mango/scripts/generate-tagrules.sh
#
#  Needs mango RUNNING (it queries the live compositor for outputs via mmsg).
# =============================================================================
set -uo pipefail

# CMD lines are what docs-hub.sh's command list shows: a real, runnable command
# and a short description, separated by " :: ". They live here, next to the code
# that implements them, so the hub stores no copy of its own. Add a line when you
# add a flag worth showing; the fuller explanation stays in the Usage block above.
# CMD: ~/.config/mango/scripts/generate-tagrules.sh :: regenerate the per-monitor tagrules from the live outputs

# ---- ########## EDIT HERE AFTER A MANGO UPDATE ########## -------------------
# The query that lists connected output NAMES -- the SAME call the Window Mode
# plugin and post-update-health.sh use. If output detection breaks after a mango
# update, verify by hand:   mmsg get all-monitors | jq '.monitors[].name'
OUTPUTS_CMD=(mmsg get all-monitors)
outputs_names() { "${OUTPUTS_CMD[@]}" 2>/dev/null | jq -r '.monitors[].name' 2>/dev/null; }
TAGS_PER_MONITOR=9                 # mango has 9 tags per monitor
# ----------------------------------------------------------------------------

OUT_FILE="$HOME/.config/mango/dms/tagrules.conf"

die() { echo "generate-tagrules: $*" >&2; exit 1; }

command -v mmsg >/dev/null 2>&1 || die "mmsg not found -- is MangoWM installed and running?"
command -v jq   >/dev/null 2>&1 || die "jq not found -- install jq (it's in the DankMango package list)."

# --list-outputs: print the connected output names, one per line, and exit without
# writing anything. This exists so OTHER tools (the installer's main-display
# selector, lib/common.sh) can ask "what monitors are there?" without duplicating
# the query above -- keeping the EDIT-HERE box the single place a mango rename has
# to be fixed. Exits 1 with no output if nothing's connected, or mango isn't up.
# --help prints this script's own header block (the only copy of its usage).
# Same one-line idiom as install.sh/update.sh/uninstall.sh, so docs-hub.sh's
# command menu can shell out to it instead of storing a second description.
self_help() { awk 'NR>2 && !/^#/{exit} NR>2 && sub(/^#[ ]?/,"")' "$0"; }
case "${1:-}" in -h|--help) self_help; exit 0 ;; esac

if [ "${1:-}" = "--list-outputs" ]; then
  names="$(outputs_names | sed '/^[[:space:]]*$/d' | sort -u)"
  [ -n "$names" ] || exit 1
  printf '%s\n' "$names"
  exit 0
fi

mkdir -p "$(dirname "$OUT_FILE")"

# Collect current outputs, sorted + de-duplicated so re-runs produce an identical
# file regardless of the order mmsg happens to return them in.
mapfile -t MONITORS < <(outputs_names | sed '/^[[:space:]]*$/d' | sort -u)

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# ==========================================================================="
  echo "# tagrules.conf  --  AUTO-GENERATED by scripts/generate-tagrules.sh."
  echo "# DO NOT hand-edit: re-run that script instead (e.g. after adding or removing"
  echo "# a monitor). The Monitor Mode plugin / set-monitor-layout.sh rewrites these"
  echo "# lines when you pick a different layout for a monitor."
  echo "# Generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "#"
  echo "# One 9-line block per connected monitor, all starting on TILE. A monitor's"
  echo "# layout is the layout_name on its rules."
  echo "# Sourced by config.conf:  source=~/.config/mango/dms/tagrules.conf"
  echo "# ==========================================================================="
  if [ "${#MONITORS[@]}" -eq 0 ]; then
    echo "# (no connected outputs detected at generation time -- is mango running?)"
  fi
  for mon in "${MONITORS[@]}"; do
    echo ""
    echo "# --- $mon (tile) ---"
    for id in $(seq 1 "$TAGS_PER_MONITOR"); do
      echo "tagrule = id:$id, monitor_name:$mon, layout_name:tile"
    done
  done
} > "$TMP"

mv "$TMP" "$OUT_FILE"

# --- summary ----------------------------------------------------------------
if [ "${#MONITORS[@]}" -eq 0 ]; then
  echo "generate-tagrules: WARNING -- no outputs detected; wrote a header-only $OUT_FILE."
  echo "                   Is mango running? Re-run this once your session is up."
  exit 0
fi
echo "generate-tagrules: detected ${#MONITORS[@]} monitor(s): ${MONITORS[*]}"
echo "                   wrote $(( ${#MONITORS[@]} * TAGS_PER_MONITOR )) tagrule line(s), all TILE -> $OUT_FILE"
echo "                   reload mango to apply:  mmsg dispatch reload_config   (or Super+r)"
