#!/usr/bin/env bash
# =============================================================================
#  wallpaper-accent-extract.sh -- pull TWO genuinely distinct accent colours
#                                 out of the current wallpaper
# =============================================================================
#  WHY THIS EXISTS
#    DMS/matugen derives its whole palette from ONE seed (source-color-index 0),
#    so every Theme role ends up in that seed's hue family. dank16 doesn't help
#    either -- it's generated by the dms binary and doesn't vary with the matugen
#    scheme at all. Result: the cava visualiser's gradient was picking colours
#    with no visible relationship to the wallpaper.
#
#    matugen can extract up to 5 ranked dominant colours (--source-color-index
#    0-4). Those ARE the wallpaper's real colours. This script asks for each,
#    scores every pair for visual distance, and records the winner.
#
#  OUTPUT  ~/.cache/mango/accent-pair.json
#    {"ok":true,"a":"#11579b","b":"#fc9d60","candidates":[...],"wallpaper":"..."}
#    ok=false when the image yields fewer than 2 candidates (happens on
#    low-complexity wallpapers) -- the widget then falls back to its own scoring.
#
#  COST  up to 5 matugen runs per wallpaper change. All --dry-run, so matugen
#        writes nothing itself; the only output is this script's small JSON.
# =============================================================================
set -uo pipefail

# --help prints this script's own header block (the only copy of its usage).
# Same one-line idiom as install.sh/update.sh/uninstall.sh, so docs-hub.sh's
# command menu can shell out to it instead of storing a second description.
#
# Above the matugen/jq guards on purpose: those `|| exit 1` lines would make
# --help exit non-zero (and say nothing) on a machine missing either tool.
self_help() { awk 'NR>2 && !/^#/{exit} NR>2 && sub(/^#[ ]?/,"")' "$0"; }
case "${1:-}" in -h|--help) self_help; exit 0 ;; esac

STATE_JSON="$HOME/.local/state/DankMaterialShell/session.json"
SETTINGS="$HOME/.config/DankMaterialShell/settings.json"
OUT_DIR="$HOME/.cache/mango"
OUT="$OUT_DIR/accent-pair.json"

command -v matugen >/dev/null 2>&1 || exit 1
command -v jq      >/dev/null 2>&1 || exit 1

# Current wallpaper: try the obvious keys, then fall back to scanning the state
# file for any image path (DMS has moved this key before).
wallpaper_path() {
    local wp
    wp="$(jq -r '.wallpaperPath // .wallpaper // empty' "$STATE_JSON" 2>/dev/null)"
    if [ -n "$wp" ] && [ -f "$wp" ]; then printf '%s' "$wp"; return 0; fi
    wp="$(jq -r '..|strings|select(test("\\.(png|jpe?g|webp)$"))' "$STATE_JSON" 2>/dev/null | head -1)"
    if [ -n "$wp" ] && [ -f "$wp" ]; then printf '%s' "$wp"; return 0; fi
    return 1
}

WP="$(wallpaper_path)" || exit 1
mkdir -p "$OUT_DIR" 2>/dev/null

# Match whatever scheme DMS is themed with, so the seeds we score are the same
# ones DMS would have used had it asked for them.
SCHEME="$(jq -r '.matugenScheme // "scheme-tonal-spot"' "$SETTINGS" 2>/dev/null)"
[ -n "$SCHEME" ] && [ "$SCHEME" != "null" ] || SCHEME="scheme-tonal-spot"

cands=()
for i in 0 1 2 3 4; do
    c="$(matugen image "$WP" --dry-run -j hex -q -t "$SCHEME" --source-color-index "$i" 2>/dev/null \
         | jq -r '.colors.source_color.dark.color // empty')"
    # Not every image yields 5 candidates; missing indices return empty. Skip them.
    case "$c" in "#"??????) cands+=("$c") ;; esac
done

if [ "${#cands[@]}" -lt 2 ]; then
    printf '{"ok":false,"reason":"fewer than 2 candidates","wallpaper":"%s"}\n' "$WP" > "$OUT"
    exit 0
fi

# Same scoring the widget already used for dank16: wrap-aware hue distance
# dominates, lightness/saturation break near-ties, greys fall back to lightness.
printf '%s\n' "${cands[@]}" | WP="$WP" python3 -c '
import sys, os, json, colorsys, itertools
cands = [l.strip() for l in sys.stdin if l.strip()]
def hsl(h):
    r, g, b = (int(h[i:i+2], 16) / 255 for i in (1, 3, 5))
    H, L, S = colorsys.rgb_to_hls(r, g, b)
    return H, S, L
def score(a, b):
    ha, sa, la = hsl(a); hb, sb, lb = hsl(b)
    dh = 0.0 if (sa < 0.08 or sb < 0.08) else min(abs(ha - hb), 1.0 - abs(ha - hb))
    return dh * 2.0 + abs(la - lb) * 0.6 + abs(sa - sb) * 0.2
pairs = list(itertools.combinations(range(len(cands)), 2))
i, j = max(pairs, key=lambda p: score(cands[p[0]], cands[p[1]]) - (p[0] + p[1]) * 0.001)
print(json.dumps({"ok": True, "a": cands[i], "b": cands[j],
                  "score": round(score(cands[i], cands[j]), 4),
                  "candidates": cands, "wallpaper": os.environ.get("WP", "")}))
' > "$OUT.tmp" 2>/dev/null && mv "$OUT.tmp" "$OUT" || { rm -f "$OUT.tmp"; exit 1; }
exit 0
